### ISSUE TITLE
[WEBSITE] Landing Page Dokter - Button "Download Sekarang"

### ISSUE THREAD

**Issue by larasmaharani** [Capstone-Mental-Health-Care-Group-6/qe-capstone#1]

**Comment by larasmaharani** [comment]
Button "Download Sekarang" harusnya "Daftar Sekarang"

![Image](https://github.com/Capstone-Mental-Health-Care-Group-6/qe-capstone/assets/120534414/a5b5d7eb-707a-4728-a764-754b360857b6)

**Comment by kareeem-dev** [comment]
untuk revisinya udah kami perbaiki ya, dan udah kami deploy ulang, jadi bisa di cek lagi.
